import { LeadType, Prisma } from '@prisma/client';

type SeedPage = {
  slug: string;
  title: string;
  eyebrow: string;
  seoTitle: string;
  seoDescription: string;
  lede: string;
  template: string;
  leadType?: LeadType;
  registerKind?: string;
  productKey?: string;
  navGroup: string;
  navLabel: string;
  sortOrder: number;
  body: Prisma.InputJsonValue;
};

function sections(...items: Array<Record<string, unknown>>): Prisma.InputJsonValue {
  return JSON.parse(JSON.stringify({ sections: items })) as Prisma.InputJsonValue;
}

export const CMS_SITE_DEFAULT = {
  name: 'KarnaCab',
  tagline: 'Bike, auto, and cab across Bihar',
  footerBlurb:
    'Rides, parcel, travel packages, bulk and corporate transport. Fares and packages come from the KarnaCab API — Admin can change them without a website deploy.',
  contactEmail: '',
  contactPhone: '',
  canonicalHost: '',
  defaultSeoTitle: 'KarnaCab — rides, parcel and travel in Bihar',
  defaultSeoDescription:
    'Book or request Local Cab, One Way, Round Way, rental, airport, railway, parcel, travel packages, bulk and corporate trips with KarnaCab.',
  ogImage: '',
};

export const CMS_HOME_PROMO_DEFAULT = {
  title: 'Railway station pickup',
  subtitle: 'Station transfers listed from the live ride catalog',
  cta: 'See railway',
  href: '/railway',
};

export const CMS_PAGES_SEED: SeedPage[] = [
  {
    slug: 'home',
    title: 'Ride when you need to go',
    eyebrow: 'KarnaCab',
    seoTitle: 'KarnaCab — Bihar rides, parcel and travel',
    seoDescription:
      'Public KarnaCab website for customer ride requests, travel packages, parcel, bulk, corporate, drivers, fleet, franchise and ads.',
    lede: 'KarnaCab is Bihar mobility: city rides, outstation, parcel, travel packages, bulk booking and corporate transport.',
    template: 'home',
    navGroup: 'primary',
    navLabel: 'Home',
    sortOrder: 1,
    body: sections(
      {
        heading: 'How it works',
        text: 'Set pickup and drop, preview the map, then send a booking request. Confirmed trips and fares use the KarnaCab API.',
        steps: [
          { title: 'Choose a service', text: 'Local cab, one way, parcel, travel and more — titles come from the live catalog.' },
          { title: 'Preview or quote', text: 'Map routes on Get route. Ride estimates use server fare rules, not page copy.' },
          { title: 'Send a request', text: 'Guests submit a lead. App customers can confirm a booking after sign-in.' },
        ],
      },
      {
        heading: 'Need a path across town?',
        text: 'Open Get route for a map preview, or pick a product page to request a trip.',
        ctaLabel: 'Get route',
        ctaHref: '/route',
      },
    ),
  },
  {
    slug: 'rides',
    title: 'Rides',
    eyebrow: 'Vehicles',
    seoTitle: 'Bike, auto and cab | KarnaCab',
    seoDescription: 'Vehicle categories from the live KarnaCab catalog.',
    lede: 'Bike, auto, cab and other categories from the ride catalog. Seats and labels are not hard-coded on this page.',
    template: 'rides',
    navGroup: 'primary',
    navLabel: 'Rides',
    sortOrder: 2,
    body: sections({ heading: 'Choose a vehicle', text: 'Then open a product such as Local Cab or One Way to request a trip.' }),
  },
  {
    slug: 'about',
    title: 'About KarnaCab',
    eyebrow: 'Company',
    seoTitle: 'About KarnaCab',
    seoDescription: 'KarnaCab is a Bihar ride, parcel and travel platform for customers, drivers and partners.',
    lede: 'One platform for customers, captains, fleet owners, franchisees and advertisers.',
    template: 'legal',
    navGroup: 'company',
    navLabel: 'About',
    sortOrder: 10,
    body: sections(
      {
        heading: 'What we operate',
        text: 'Bike taxi, auto and cab products, local and Bihar parcel, published travel packages, bulk events and corporate billing. Service lists, districts and package prices are stored in Admin, not in this page.',
      },
      {
        heading: 'Who it is for',
        text: 'People who need a reliable trip, captains who want documented onboarding, and businesses that need GST-ready transport.',
      },
    ),
  },
  {
    slug: 'how-it-works',
    title: 'How KarnaCab works',
    eyebrow: 'Guide',
    seoTitle: 'How KarnaCab works',
    seoDescription: 'Preview a route, request a ride or parcel, and complete bookings in the KarnaCab app.',
    lede: 'Plan on the website. Live matching and payments run through the same API as the mobile apps.',
    template: 'legal',
    navGroup: 'company',
    navLabel: 'How it works',
    sortOrder: 11,
    body: sections(
      {
        heading: 'Three steps',
        steps: [
          { title: 'Enter pickup and drop', text: 'Use Get route or a product page. Add a landmark if the street name is common.' },
          { title: 'Pick a product and vehicle', text: 'Ride types and vehicles are listed from the ride catalog, including rental hours from fare rules.' },
          { title: 'Request or book', text: 'Send a website request, or sign in on the customer app to confirm a booking and pay.' },
        ],
      },
    ),
  },
  {
    slug: 'safety',
    title: 'Safety on every trip',
    eyebrow: 'Trust',
    seoTitle: 'KarnaCab safety',
    seoDescription: 'Driver KYC, trip sharing and support on the KarnaCab platform.',
    lede: 'Trip data, driver records and support live in one platform.',
    template: 'legal',
    navGroup: 'company',
    navLabel: 'Safety',
    sortOrder: 12,
    body: sections(
      {
        heading: 'Verified captains',
        text: 'Driver documents and KYC status are managed in operations. Required document types are Admin settings, not website copy.',
      },
      {
        heading: 'Support',
        text: 'Use the Support page for FAQs from the help catalog, or send a message. In-trip SOS uses the safety API after a booking is live.',
      },
    ),
  },
  {
    slug: 'local-cab',
    title: 'Local Cab',
    eyebrow: 'Ride',
    seoTitle: 'Local Cab in Bihar | KarnaCab',
    seoDescription: 'City rides with fares from Admin fare rules. Request a Local Cab on KarnaCab.',
    lede: 'City rides across Bihar. Min KM, per-KM, waiting, night, toll, parking and GST come from Admin fare rules — not this page.',
    template: 'service',
    leadType: LeadType.RIDE,
    productKey: 'LOCAL_CAB',
    navGroup: 'rides',
    navLabel: 'Local cab',
    sortOrder: 20,
    body: sections({ heading: 'Request a local cab', text: 'Submit a booking request or preview a map route. Quote totals are calculated by the API.' }),
  },
  {
    slug: 'one-way',
    title: 'One Way',
    eyebrow: 'Ride',
    seoTitle: 'One Way cab | KarnaCab',
    seoDescription: 'Point-to-point One Way trips. Server quotes from fare rules.',
    lede: 'Point-to-point trips. Request a quote from the fare engine, then send a booking request.',
    template: 'service',
    leadType: LeadType.RIDE,
    productKey: 'ONE_WAY',
    navGroup: 'rides',
    navLabel: 'One way',
    sortOrder: 21,
    body: sections({ heading: 'One Way', text: 'Pickup, drop, vehicle category and distance go to POST /quotes/ride with product ONE_WAY.' }),
  },
  {
    slug: 'round-way',
    title: 'Round Way',
    eyebrow: 'Ride',
    seoTitle: 'Round Way cab | KarnaCab',
    seoDescription: 'Round Way trips with return planning. Fares from Admin rules.',
    lede: 'Outbound and return on one booking. Driver allowance and extra KM follow Admin fare rules.',
    template: 'service',
    leadType: LeadType.RIDE,
    productKey: 'ROUND_WAY',
    navGroup: 'rides',
    navLabel: 'Round way',
    sortOrder: 22,
    body: sections({ heading: 'Round Way', text: 'Include return details in your requirement so operations can quote from live rules.' }),
  },
  {
    slug: 'rental',
    title: 'Rental',
    eyebrow: 'Ride',
    seoTitle: 'Cab rental packages | KarnaCab',
    seoDescription: 'Hourly rental packages from Admin fare rules, including included KM.',
    lede: 'Hourly packages with included KM. Hours and prices are listed from the live rental catalog, not hard-coded here.',
    template: 'service',
    leadType: LeadType.RIDE,
    productKey: 'RENTAL',
    navGroup: 'rides',
    navLabel: 'Rental',
    sortOrder: 23,
    body: sections({ heading: 'Rental hours', text: 'Choose a package shown on this page from GET /ride-engine/rental-packages.' }),
  },
  {
    slug: 'schedule',
    title: 'Schedule',
    eyebrow: 'Ride',
    seoTitle: 'Schedule a cab | KarnaCab',
    seoDescription: 'Book a future pickup. Reminder and assignment lead times are Admin settings.',
    lede: 'Book a future date and time. Reminder and assignment windows are Admin schedule settings.',
    template: 'service',
    leadType: LeadType.RIDE,
    productKey: 'SCHEDULE',
    navGroup: 'rides',
    navLabel: 'Schedule',
    sortOrder: 24,
    body: sections({ heading: 'Schedule a ride', text: 'Tell us the pickup time in your request. The customer app can also create a SCHEDULE booking when you are signed in.' }),
  },
  {
    slug: 'outstation',
    title: 'Outstation',
    eyebrow: 'Ride',
    seoTitle: 'Outstation cab from Bihar | KarnaCab',
    seoDescription: 'Intercity Outstation trips. Districts and fares from the KarnaCab catalog.',
    lede: 'Intercity travel from Bihar districts listed in the platform catalog.',
    template: 'service',
    leadType: LeadType.RIDE,
    productKey: 'OUTSTATION',
    navGroup: 'rides',
    navLabel: 'Outstation',
    sortOrder: 25,
    body: sections({ heading: 'Outstation', text: 'Pick origin district from the live district list when you send a request.' }),
  },
  {
    slug: 'airport',
    title: 'Airport',
    eyebrow: 'Transfer',
    seoTitle: 'Airport cab pickup and drop | KarnaCab',
    seoDescription: 'Airport transfers. Flight details can be added on the booking.',
    lede: 'Airport pickup and drop. Transfer policy and fares come from the ride engine catalog.',
    template: 'service',
    leadType: LeadType.RIDE,
    productKey: 'AIRPORT',
    navGroup: 'rides',
    navLabel: 'Airport',
    sortOrder: 26,
    body: sections({ heading: 'Airport transfer', text: 'Include flight number and terminal in your requirement when you have them.' }),
  },
  {
    slug: 'railway',
    title: 'Railway',
    eyebrow: 'Transfer',
    seoTitle: 'Railway station cab | KarnaCab',
    seoDescription: 'Station pickup and drop. Train number can be stored on the booking.',
    lede: 'Station pickup and drop. Vehicles and policy come from the live ride catalog.',
    template: 'service',
    leadType: LeadType.RIDE,
    productKey: 'RAILWAY',
    navGroup: 'rides',
    navLabel: 'Railway',
    sortOrder: 27,
    body: sections({ heading: 'Railway transfer', text: 'Include train number and station name in your request.' }),
  },
  {
    slug: 'parcel',
    title: 'Parcel',
    eyebrow: 'Delivery',
    seoTitle: 'Local parcel delivery | KarnaCab',
    seoDescription: 'Local parcel with types and vehicles from Admin parcel catalog.',
    lede: 'Pickup to drop for permitted goods. Parcel types, prohibited items and fares come from the parcel catalog.',
    template: 'service',
    leadType: LeadType.PARCEL,
    navGroup: 'services',
    navLabel: 'Parcel',
    sortOrder: 30,
    body: sections({ heading: 'Local parcel', text: 'Restricted goods listed in Admin settings are not accepted. OTP delivery follows the parcel API after you book in the app.' }),
  },
  {
    slug: 'bihar-parcel',
    title: 'Bihar Parcel',
    eyebrow: 'Delivery',
    seoTitle: 'Bihar district parcel | KarnaCab',
    seoDescription: 'District-to-district parcel. Policy from Admin parcel settings.',
    lede: 'District-to-district and city-to-city. Restricted goods follow the same Admin prohibited list as local parcel.',
    template: 'service',
    leadType: LeadType.BIHAR_PARCEL,
    navGroup: 'services',
    navLabel: 'Bihar parcel',
    sortOrder: 31,
    body: sections({ heading: 'Bihar Parcel', text: 'Name origin and destination districts from the live district list.' }),
  },
  {
    slug: 'travel',
    title: 'Travel Packages',
    eyebrow: 'KarnaTravel',
    seoTitle: 'Travel packages in Bihar | KarnaCab',
    seoDescription: 'Published darshan, sightseeing and hotel+cab packages from Admin.',
    lede: 'Published packages only. Categories, itineraries and prices are Admin-managed KarnaTravel records.',
    template: 'travel',
    leadType: LeadType.TRAVEL,
    navGroup: 'services',
    navLabel: 'Travel',
    sortOrder: 32,
    body: sections({ heading: 'Discover packages', text: 'Browse published packages below. Send an enquiry if you want a custom date or group size.' }),
  },
  {
    slug: 'bulk-booking',
    title: 'Bulk Booking',
    eyebrow: 'Events',
    seoTitle: 'Bulk cab booking | KarnaCab',
    seoDescription: 'Multiple vehicles for weddings, schools and events. Event types from Admin.',
    lede: 'Multiple vehicles for weddings, schools, corporate and group tours. Event types and rates come from the bulk catalog.',
    template: 'service',
    leadType: LeadType.BULK,
    navGroup: 'services',
    navLabel: 'Bulk booking',
    sortOrder: 33,
    body: sections({ heading: 'Bulk enquiry', text: 'Tell us event type, date, vehicle count and districts. A quotation uses Admin bulk rate rules.' }),
  },
  {
    slug: 'corporate',
    title: 'Corporate',
    eyebrow: 'Business',
    seoTitle: 'Corporate cab and GST billing | KarnaCab',
    seoDescription: 'Employee transport, monthly cabs and GST invoices for Bihar companies.',
    lede: 'Employee transport, monthly cabs, GST invoices and reports. Company profile is configured in the corporate API after you enquire.',
    template: 'service',
    leadType: LeadType.CORPORATE,
    navGroup: 'primary',
    navLabel: 'Corporate',
    sortOrder: 5,
    body: sections({ heading: 'Corporate enquiry', text: 'Share GSTIN, city and expected monthly trips. Operations will open a corporate account when approved.' }),
  },
  {
    slug: 'drive',
    title: 'Drive With Us',
    eyebrow: 'Captains',
    seoTitle: 'Drive with KarnaCab',
    seoDescription: 'Register as a KarnaCab driver. KYC document list is Admin-configured.',
    lede: 'Create a captain account, then complete KYC in the driver app. Required documents are Admin settings.',
    template: 'register',
    registerKind: 'driver',
    navGroup: 'company',
    navLabel: 'Drive with us',
    sortOrder: 40,
    body: sections({ heading: 'Captain signup', text: 'Registration creates a DRIVER user. Licence number is required. Document upload happens after login in the driver app.' }),
  },
  {
    slug: 'fleet-partner',
    title: 'Fleet Partner',
    eyebrow: 'Partners',
    seoTitle: 'Fleet partner with KarnaCab',
    seoDescription: 'Operate multiple vehicles and drivers under one fleet owner account.',
    lede: 'Manage multiple vehicles and drivers under one fleet owner account.',
    template: 'service',
    leadType: LeadType.FLEET,
    registerKind: 'fleet',
    navGroup: 'company',
    navLabel: 'Fleet partner',
    sortOrder: 41,
    body: sections({ heading: 'Fleet enquiry', text: 'Tell us city, vehicle count and categories. Operations creates the fleet owner login after review.' }),
  },
  {
    slug: 'franchise',
    title: 'Franchise',
    eyebrow: 'Network',
    seoTitle: 'District franchise | KarnaCab',
    seoDescription: 'Apply for a district franchise. One active exclusive seat per district.',
    lede: 'One district has one active District Head or Exclusive Franchise. Apply with KYC after operations opens your login.',
    template: 'service',
    leadType: LeadType.FRANCHISE,
    registerKind: 'franchise',
    navGroup: 'primary',
    navLabel: 'Franchise',
    sortOrder: 6,
    body: sections({ heading: 'Franchise application', text: 'Send an enquiry with preferred district. Formal apply + documents use POST /franchise/apply once you have an account.' }),
  },
  {
    slug: 'advertise',
    title: 'Advertise With Us',
    eyebrow: 'KarnaCab Ads',
    seoTitle: 'Advertise with KarnaCab',
    seoDescription: 'City and district campaigns. Ads stay out of an active ride flow.',
    lede: 'City and district campaigns. Impression and click rates are Admin settings. Ads never inject into an active trip screen.',
    template: 'register',
    leadType: LeadType.ADVERTISE,
    registerKind: 'advertiser',
    navGroup: 'company',
    navLabel: 'Advertise',
    sortOrder: 42,
    body: sections({ heading: 'Advertiser account', text: 'Register an advertiser login, or send an enquiry if you want operations to brief you first.' }),
  },
  {
    slug: 'contact',
    title: 'Contact',
    eyebrow: 'Hello',
    seoTitle: 'Contact KarnaCab',
    seoDescription: 'Contact KarnaCab for rides, partners and website help.',
    lede: 'Questions about the website, a booking request, or a partner account — write here.',
    template: 'contact',
    leadType: LeadType.SUPPORT,
    navGroup: 'primary',
    navLabel: 'Contact',
    sortOrder: 7,
    body: sections({ heading: 'We reply from operations', text: 'Messages are stored as support leads. Do not send payment card numbers.' }),
  },
  {
    slug: 'support',
    title: 'Support',
    eyebrow: 'Help',
    seoTitle: 'KarnaCab support and FAQ',
    seoDescription: 'Customer FAQs from the help catalog plus a support request form.',
    lede: 'Answers from the live FAQ catalog. Signed-in app users can also open tickets on the support API.',
    template: 'support',
    leadType: LeadType.SUPPORT,
    navGroup: 'company',
    navLabel: 'Support',
    sortOrder: 13,
    body: sections({ heading: 'Still stuck?', text: 'Send a support request. Booking-linked complaints belong in the customer app so they attach to the trip.' }),
  },
  {
    slug: 'terms',
    title: 'Terms',
    eyebrow: 'Legal',
    seoTitle: 'KarnaCab terms of use',
    seoDescription: 'Terms for the public KarnaCab website, quotes and partner applications.',
    lede: 'Using the KarnaCab website, map routes, quotes and lead forms.',
    template: 'legal',
    navGroup: 'legal',
    navLabel: 'Terms',
    sortOrder: 90,
    body: sections(
      {
        heading: 'Website and estimates',
        text: 'Map routes are estimates from OpenStreetMap data. Fare quotes are server calculations from Admin fare rules. Neither is a promise of a driver until a booking is confirmed on the API.',
      },
      {
        heading: 'Accounts',
        text: 'Website session accounts and KarnaCab API accounts may be separate until you sign in on the customer or driver app. Partner applications are reviewed by operations.',
      },
    ),
  },
  {
    slug: 'privacy',
    title: 'Privacy',
    eyebrow: 'Legal',
    seoTitle: 'KarnaCab privacy',
    seoDescription: 'How the public website handles names, phones, routes and leads.',
    lede: 'How the public website handles the information you type.',
    template: 'legal',
    navGroup: 'legal',
    navLabel: 'Privacy',
    sortOrder: 91,
    body: sections(
      {
        heading: 'What we collect on this site',
        text: 'Account registration on the website stores name, email and a password hash for session login. Lead forms send name, phone, optional email, district and message to the KarnaCab API.',
      },
      {
        heading: 'Maps',
        text: 'Pickup and drop text is sent to OpenStreetMap Nominatim and OSRM to draw a route. Those searches are not stored as trip bookings.',
      },
    ),
  },
];
